In [3]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from eu_survey_correlation.surveys.ess_scraper import ESSCodebookParser
import os

In [11]:
ess_datapath = "data/surveys/ess"
all_questions_df = pd.DataFrame()
for ess_dir in os.listdir(ess_datapath):
    dir_path = ess_datapath + f"/{ess_dir}"
    for filename in os.listdir(dir_path):
        if filename.endswith(".html"):
            filepath = dir_path + f"/{filename}"
            parser = ESSCodebookParser(filepath)
            df = parser.parse()
            df["ess_id"] = ess_dir
            all_questions_df = pd.concat([all_questions_df, df]).reset_index(drop=True)

In [12]:
all_questions_df

,variable_id,variable_name,variable_description,answer_id,answer_value,ess_id
0,name,Title of dataset,,None,None,ESS3e03_7
1,essround,ESS round,,None,None,ESS3e03_7
2,edition,Edition,,None,None,ESS3e03_7
3,proddate,Production date,,None,None,ESS3e03_7
4,idno,Respondent's identification number,,None,None,ESS3e03_7
...,...,...,...,...,...,...
125860,supqad2,Administration of supplementary questionnaire 2,,9,Not available*,ESS7e02_3
125861,supqdd,"Day of month, supplementary questionnaire",,99,Not available*,ESS7e02_3
125862,supqmm,"Month, supplementary questionnaire",,99,Not available*,ESS7e02_3
125863,supqyr,"Year, supplementary questionnaire",,9999,Not available*,ESS7e02_3
125864,inwtm,"Interview length in minutes, main questionnaire","Interview length in minutes, main questionnair...",None,None,ESS7e02_3

In [ ]:
unique_variables_df = all_questions_df[
    ["variable_id", "variable_name", "variable_description"]
].drop_duplicates()

In [20]:
unique_variables_df.variable_description.value_counts()

variable_description
                                                                                                                                                                                                                                                                                     124
Which one? (Poland)                                                                                                                                                                                                                                                                   19
Which one? (Switzerland)                                                                                                                                                                                                                                                              18
Which one? (Hungary)                                                                                                                                                                                                                                                                  16
Which one? (Portugal)                                                                                                                                                                                                                                                                 15
                                                                                                                                                                                                                                                                                    ...
Regardless of your basic or contracted hours, how many hours do/did you normally work a week (in your main job), including any paid or unpaid overtimeWRITE IN HOURS:                                                                                                                  1
Have any of these periods been within the past 5 years?NOTE TO INTERVIEWER: these periods refer to the periods of more than 3 months at F27.                                                                                                                                           1
CARD 45Please consider the income of all household members and any income which may be received by the household as a whole. What is the main source of income in your household?Please use this card.                                                                                 1
CARD 46Using this card, if you add up the income from all sources, which letter describes your household's total net income? If you don't know the exact figure, please give an estimate. Use the part of the card that you know best: weekly, monthly or annual income.               1
How would you describe your ancestry? Ancestry 2INTERVIEWER: code maximum of two ancestries in total. If more than two are mentioned, ask respondent to select two. If respondent is unable to do this, code first two ancestries mentioned. INTERVIEWER PROBE ONCE: Which other?      1
Name: count, Length: 3624, dtype: int64

In [ ]:
all_questions_df[all_questions_df.variable_id == "hinctnta"].answer_value.unique()

array(['J - 1st decile', 'R - 2nd decile', 'C - 3rd decile',
       'M - 4th decile', 'F - 5th decile', 'S - 6th decile',
       'K - 7th decile', 'P - 8th decile', 'D - 9th decile',
       'H - 10th decile', 'Refusal*', "Don't know*", 'No answer*'],
      dtype=object)

In [37]:
all_questions_df

,variable_id,variable_name,variable_description,answer_id,answer_value,ess_id
0,name,Title of dataset,,None,None,ESS3e03_7
1,essround,ESS round,,None,None,ESS3e03_7
2,edition,Edition,,None,None,ESS3e03_7
3,proddate,Production date,,None,None,ESS3e03_7
4,idno,Respondent's identification number,,None,None,ESS3e03_7
...,...,...,...,...,...,...
125860,supqad2,Administration of supplementary questionnaire 2,,9,Not available*,ESS7e02_3
125861,supqdd,"Day of month, supplementary questionnaire",,99,Not available*,ESS7e02_3
125862,supqmm,"Month, supplementary questionnaire",,99,Not available*,ESS7e02_3
125863,supqyr,"Year, supplementary questionnaire",,9999,Not available*,ESS7e02_3
125864,inwtm,"Interview length in minutes, main questionnaire","Interview length in minutes, main questionnair...",None,None,ESS7e02_3

In [ ]:
unique_variables_df[
    unique_variables_df.variable_name
    == "Imagine large numbers of people limit energy use, how likely reduce climate change"
].variable_description.tolist()

['CARD 43Now imagine that large numbers of people limited their energy use. How likely do you think it is that this would reduce climate change?',
 'ASK IF GROUP 1 AT C33 (IF C33 = 1) \nCARD 32Now imagine that large numbers of people limited their energy use. How likely do you think it is that this would reduce climate change?',
 'ASK IF GROUP 2 AT C33 (IF C33 = 2)\nCARD 33Now imagine that large numbers of people limited their energy use. How likely do you think it is that this would reduce climate change?',
 'ASK IF GROUP 3 AT C33 (IF C33 = 3)\nCARD 34Now imagine that large numbers of people limited their energy use. How likely do you think it is that this would reduce climate change?',
 'ASK IF GROUP 1 AT C33 (IF C33 = 1)\nTo help us improve our questions in the future, here are some questions which are similar to previous ones. Please don’t try to remember what you answered before but treat them as if they were completely new questions.\nCARD 86Now imagine that large numbers of people limited their energy use. How likely do you think it is that this would reduce climate change?',
 'ASK IF GROUP 2 AT C33 (IF C33 = 2)\nTo help us improve our questions in the future, here are some questions which are similar to previous ones. Please don’t try to remember what you answered before but treat them as if they  were completely new questions.\nCARD 87Now imagine that large numbers of people limited their energy use. How likely do you think it is that this would reduce climate change?',
 'ASK IF GROUP 3 AT C33 (IF C33 = 3) \nTo help us improve our questions in the future, here are some questions which are similar to previous ones. Please don’t try to remember what you answered before but treat them as if they were completely new questions.\nCARD 88Now imagine that large numbers of people limited their energy use. How likely do you think it is that this would reduce climate change?',
 'CARD 30Now imagine that large numbers of people limited their energy use. How likely do you think it is that this would reduce climate change?',
 'CARD 31Now imagine that large numbers of people limited their energy use. How likely do you think it is that this would reduce climate change?',
 'CARD 32Now imagine that large numbers of people limited their energy use. How likely do you think it is that this would reduce climate change?',
 "To help us improve our questions in the future, here are some questions which are similar to previous ones. Please don't try to remember what you answered before but treat them as if they were completely new questions.\nCARD 90Now imagine that large numbers of people limited their energy use. How likely do you think it is that this would reduce climate change?",
 "To help us improve our questions in the future, here are some questions which are similar to previous ones. Please don't try to remember what you answered before but treat them as if they were completely new questions.\nCARD 91Now imagine that large numbers of people limited their energy use. How likely do you think it is that this would reduce climate change?",
 "To help us improve our questions in the future, here are some questions which are similar to previous ones. Please don't try to remember what you answered before but treat them as if they were completely new questions.\nCARD 92Now imagine that large numbers of people limited their energy use. How likely do you think it is that this would reduce climate change?"]

In [45]:
unique_variables_df.variable_description.unique().tolist()

['',
 'CARD 1On an average weekday, how much time, in total, do you spend watching television?Please use this card to answer.',
 'STILL CARD 1And again on an average weekday, how much of your time watching television is spent watching news or programmes about politics and current affairs?Still use this card.',
 'ASK ALL STILL CARD 1On an average weekday, how much time, in total, do you spend listening to the radio?Use the same card.',
 'STILL CARD 1And again on an average weekday, how much of your time listening to the radio is spent listening to news or programmes about politics and current affairs?Still use this card.',
 'ASK ALL STILL CARD 1On an average weekday, how much time, in total, do you spend reading the newspapers?Use this card again.',
 'STILL CARD 1And how much of this time is spent reading about politics and current affairs?Still use this card.',
 'ASK ALL CARD 2Now, using this card, how often do you use the internet, the World Wide Web or e-mail - whether at home or at work - for your personal use?',
 "CARD 3Using this card, generally speaking, would you say that most people can be trusted, or that you can't be too careful in dealing with people? Please tell me on a score of 0 to 10, where 0 means you can't be too careful and 10 means that most people can be trusted.",
 'CARD 4Using this card, do you think that most people would try to take advantage of you if they got the chance, or would they try to be fair?',
 'CARD 5Would you say that most of the time people try to be helpful or that they are mostly looking out for themselves?Please use this card.',
 'How interested would you say you are in politics - are you...READ OUT...',
 "CARD 6How often does politics seem so complicated that you can't really understand what is going on?Please use this card.",
 'CARD 7How difficult or easy do you find it to make your mind up about political issues?Please use this card.',
 "CARD 8Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...[country]'s parliament?READ OUT...",
 'CARD 8Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...the legal system?READ OUT...',
 'CARD 8Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...the police?READ OUT...',
 'CARD 8Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...politicians?READ OUT...',
 'CARD 8Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...political parties?READ OUT...',
 'CARD 8Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...the European Parliament?READ OUT...',
 'CARD 8Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...the United Nations?READ OUT...',
 "Some people don't vote nowadays for one reason or another. Did you vote in the last [country] national election in [month/year]?",
 'Which party did you vote for in that election? (Austria)',
 'Which party did you vote for in that election? (Belgium)',
 'Which party did you vote for in that election? (Bulgaria)',
 'Which party did you vote for in that election? (Switzerland)',
 'Which party did you vote for in that election? (Cyprus)',
 'Which party did you vote for in that election? (Germany 1)',
 'Which party did you vote for in that election? (Germany 2)',
 'Which party did you vote for in that election? (Denmark)',
 'Which party did you vote for in that election? (Estonia)',
 'Which party did you vote for in that election? (Spain)',
 'Which party did you vote for in that election? (Finland)',
 'Which party did you vote for in that election? (France)',
 'Which party did you vote for in that election? (United Kingdom)',
 'Which party did you vote for in that election? (Hungary)',
 'Which party did you vote for in that election? (Ireland)',
 'Which party did you vote for in that election? (Latvia)',
 'Which party did you vote for in that election? (Netherlands)',
 'Which party did you vote for in that election? (Norway)',
 'Which party did you vote for in that election? (Poland)',
 'Which party did you vote for in that election? (Portugal)',
 'Which party did you vote for in that election? (Romania)',
 'Which party did you vote for in that election? (Russian Federation)',
 'Which party did you vote for in that election? (Sweden)',
 'Which party did you vote for in that election? (Slovenia)',
 'Which party did you vote for in that election? (Slovakia)',
 'Which party did you vote for in that election? (Ukraine)',
 'ASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...contacted a politician, government or local government official?READ OUT...',
 'ASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...worked in a political party or action group?READ OUT...',
 'ASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...worked in another organisation or association?READ OUT...',
 'ASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...worn or displayed a campaign badge/sticker?READ OUT...',
 'ASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...signed a petition?READ OUT...',
 'ASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...taken part in a lawful public demonstration?READ OUT...',
 'ASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...boycotted certain products?READ OUT...',
 'ASK ALLIs there a particular political party you feel closer to than all the other parties?',
 'Which one? (Austria)',
 'Which one? (Belgium)',
 'Which one? (Bulgaria)',
 'Which one? (Switzerland)',
 'Which one? (Cyprus)',
 'Which one? (Germany)',
 'Which one? (Denmark)',
 'Which one? (Estonia)',
 'Which one? (Spain)',
 'Which one? (Finland)',
 'Which one? (France)',
 'Which one? (United Kingdom)',
 'Which one? (Hungary)',
 'Which one? (Ireland)',
 'Which one? (Latvia)',
 'Which one? (Netherlands)',
 'Which one? (Norway)',
 'Which one? (Poland)',
 'Which one? (Portugal)',
 'Which one? (Romania)',
 'Which one? (Russian Federation)',
 'Which one? (Sweden)',
 'Which one? (Slovenia)',
 'Which one? (Slovakia)',
 'Which one? (Ukraine)',
 'ASK IF PARTY GIVEN AT B20b (codes 01 to xx)How close do you feel to this party? Do you feel that you are ...READ OUT...',
 'ASK ALLAre you a member of any political party?',
 "ASK ALL CARD 9In politics people sometimes talk of 'left' and 'right'. Using this card, where would you place yourself on this scale, where 0 means the left and 10 means the right?",
 'CARD 10All things considered, how satisfied are you with your life as a whole nowadays? Please answer using this card, where 0 means extremely dissatisfied and 10 means extremely satisfied.',
 'STILL CARD 10On the whole how satisfied are you with the present state of the economy in [country]?Still use this card',
 'STILL CARD 10Now thinking about the [country] government, how satisfied are you with the way it is doing its job?Still use this card',
 'STILL CARD 10And on the whole, how satisfied are you with the way democracy works in [country]?Still use this card',
 'CARD 11Now, using this card, please say what you think overall about the state of education in [country] nowadays?',
 'STILL CARD 11Still using this card, please say what you think overall about the state of health services in [country] nowadays?',
 'CARD 12Using this card, please say to what extent you agree or disagree with each of the following statements. The government should take measures to reduce differences in income levelsREAD OUT EACH STATEMENT AND CODE IN GRID',
 'CARD 12Using this card, please say to what extent you agree or disagree with each of the following statements. Gay men and lesbians should be free to live their own life as they wishREAD OUT EACH STATEMENT AND CODE IN GRID',
 'CARD 12Using this card, please say to what extent you agree or disagree with each of the following statements Political parties that wish to overthrow democracy should be bannedREAD OUT EACH STATEMENT AND CODE IN GRID',
 'CARD 12Using this card, please say to what extent you agree or disagree with each of the following statements Modern science can be relied on to solve our environmental problemsREAD OUT EACH STATEMENT AND CODE IN GRID',
 'CARD 13Now thinking about the European Union, some say European unification should go further. Others say it has already gone too far. Using this card, what number on the scale best describes your position?',
 'CARD 14Now, using this card, to what extent do you think [country] should allow people of the same race or ethnic group as most [country] people to come and live here?',
 'STILL CARD 14How about people of a different race or ethnic group from most [country] people?Still use this card',
 'STILL CARD 14How about people from the poorer countries outside Europe?Use the same card',
 "CARD 15Would you say it is generally bad or good for [country]'s economy that people come to live here from other countries?Please use this card",
 "CARD 16And, using this card, would you say that [country]'s cultural life is generally undermined or enriched by people coming to live here from other countries?",
 'CARD 17Is [country] made a worse or a better place to live by people coming to live here from other countries?Please use this card',
 'CARD 18Taking all things together, how happy would you say you are?Please use this card',
 'CARD 19Using this card, how often do you meet socially with friends, relatives or work colleagues?',
 'Do you have anyone with whom you can discuss intimate and personal matters?',
 'CARD 20Compared to other people of your age, how often would you say you take part in social activities?Please use this card',
 'Have you or a member of your household been the victim of a burglary or assault in the last 5 years?',
 'How safe do you - or would you - feel walking alone in this area after dark? Do - or would - you feel...READ OUT...',
 'CARD 21How often, if at all, do you worry about your home being burgled?Please choose your answer from this card',
 'ASK IF ANY WORRY AT C7 (CODES 1,2,3)Does this worry about your home being burgled have a...READ OUT...',
 'ASK ALL CARD 21 AGAINHow often, if at all, do you worry about becoming a victim of violent crime?Please choose your answer from this card',
 'ASK IF ANY WORRY AT C9 (CODES 1,2,3)Does this worry about becoming a victim of violent crime have a...READ OUT...',
 'ASK ALLDo you think that a terrorist attack somewhere in Europe during the next twelve months is?READ OUT...',
 'Do you think that a terrorist attack somewhere in [COUNTRY] during the next twelve months is?READ OUT...',
 'Using this card, please say how much you agree or disagree with each of these statements If a man is suspected of planning a terrorist attack in [COUNTRY], the police should have the power to keep him in prison until they are satisfied he was not involved.READ OUT EACH STATEMENT AND CODE IN GRID',
 'Using this card, please say how much you agree or disagree with each of these statements Torturing a prisoner in a [COUNTRY] prison is never justified, even if it might provide information that could prevent a terrorist attack.READ OUT EACH STATEMENT AND CODE IN GRID',
 'How is your health in general? Would you say it is ...READ OUT...',
 'Are you hampered in your daily activities in any way by any longstanding illness, or disability, infirmity or mental health problem? If yes, is that a lot or to some extent?',
 'Do you consider yourself as belonging to any particular religion or denomination?',
 'Which one?',
 'ASK IF NO RELIGION OR DENOMINATION AT C17 (codes 2 or 8 at C17)Have you ever considered yourself as belonging to any particular religion or denomination?',
 'ASK ALL CARD 23Regardless of whether you belong to a particular religion, how religious would you say you are?Please use this card',
 'CARD 24Apart from special occasions such as weddings and funerals, about how often do you attend religious services nowadays?Please use this card',
 'STILL CARD 24Apart from when you are at religious services, how often, if at all, do you pray?Please use this card',
 'ASK ALLWould you describe yourself as being a member of a group that is discriminated against in this country?',
 "On what grounds is your group discriminated against? Colour or racePROBE: 'What other grounds?' CODE ALL THAT APPLY",
 "On what grounds is your group discriminated against? NationalityPROBE: 'What other grounds?' CODE ALL THAT APPLY",
 "On what grounds is your group discriminated against? ReligionPROBE: 'What other grounds?' CODE ALL THAT APPLY",
 "On what grounds is your group discriminated against? LanguagePROBE: 'What other grounds?' CODE ALL THAT APPLY",
 "On what grounds is your group discriminated against? Ethnic groupPROBE: 'What other grounds?' CODE ALL THAT APPLY",
 "On what grounds is your group discriminated against? AgePROBE: 'What other grounds?' CODE ALL THAT APPLY",
 "On what grounds is your group discriminated against? GenderPROBE: 'What other grounds?' CODE ALL THAT APPLY",
 "On what grounds is your group discriminated against? SexualityPROBE: 'What other grounds?' CODE ALL THAT APPLY",
 "On what grounds is your group discriminated against? DisabilityPROBE: 'What other grounds?' CODE ALL THAT APPLY",
 "On what grounds is your group discriminated against? OtherPROBE: 'What other grounds?' CODE ALL THAT APPLY",
 "On what grounds is your group discriminated against? Don't knowPROBE: 'What other grounds?' CODE ALL THAT APPLY",
 "On what grounds is your group discriminated against? RefusalPROBE: 'What other grounds?' CODE ALL THAT APPLY",
 "On what grounds is your group discriminated against? Not applicablePROBE: 'What other grounds?' CODE ALL THAT APPLY",
 "On what grounds is your group discriminated against? No answerPROBE: 'What other grounds?' CODE ALL THAT APPLY",
 'ASK ALLAre you a citizen of [country]?',
 'What citizenship do you hold?WRITE IN',
 'ASK ALLWere you born in [country]?',
 'In which country were you born?WRITE IN',
 'CARD 25How long ago did you first come to live in [country]?Please use this card',
 'ASK ALLWhat language or languages do you speak most often at home? Language 1WRITE IN UP TO 2 LANGUAGES',
 'ASK ALLWhat language or languages do you speak most often at home? Language 2WRITE IN UP TO 2 LANGUAGES',
 'Do you belong to a minority ethnic group in [country]?',
 'Was your father born in [country]?',
 'In which country was your father born?WRITE IN',
 'ASK ALLWas your mother born in [country]?',
 'In which country was your mother born?WRITE IN',
 'Have you ever been in paid employment or a paid apprenticeship of 20 hours or more per week for at least 3 months?',
 'In what year did you first start working in a job like this?WRITE IN YEAR',
 'ASK ALLIn what year, if ever, did you first leave your parent(s) for 2 months or more to start living separately from them?INTERVIEWER NOTE: Parents includes any legal guardian, such as foster, step and adoptive parents. Living separately means living in separate accomodation, i.e. with a separate entrance. Include students who live separately for 2 months or more even if they return to live with parents occasionally WRITE IN YEAR',
 'Have you ever lived with a spouse or partner for three months or more?',
 'In what year did you first live with a spouse or partner for three months or more?WRITE IN YEAR',
 'ASK ALLAre you or have you ever been married?',
 'In what year did you first marry?WRITE IN YEAR',
 'ASK ALLHave you ever given birth to/fathered a child?',
 'How many children have you ever given birth to/fathered?INTERVIEWER NOTE: Include all children born alive WRITE IN',
 'In what year was your (first) child born?WRITE IN YEAR',
 'ASK IF INTERVIEWER CODE D10a = 1 (MORE THAN ONE CHILD)In what year was your youngest child born?WRITE IN YEAR',
 'ASK IF INTERVIEWER CODE D11a = 1 (CHILD BORN 1990 OR EARLIER)How many grandchildren do you have, if any?ENTER NUMBER',
 'ASK IF INTERVIEWER CODE D12a = 1 (HAS 1 OR MORE GRANDCHILDREN)In what year was your first grandchild born?WRITE IN YEAR',
 'ASK IF INTERVIEWER CODE D13a = 1 (FIRST GRANDCHILD BORN 1990 OR EARLIER)Do you have any great grandchildren?',
 "ASK ALLIn what month were you born?INTERVIEWER NOTE: Probe Don't know and Refusals ENTER MONTH",
 'Interviewer code, split ballot, ask about female or male',
 "ASK IF INTERVIEWER CODE D16a = 2People differ in their ideas about the ages at which boys or men become adults, middle-aged and old. At what age, approximately, would you say boys or men become adults?INTERVIEWER NOTE FOR ALL ITEMS ASKING FOR AN AGE: If respondent states 'it depends' accept answer and do NOT probe If respondent provides an age range, ask for a specific age within that range If respondent cannot give specific age, code as don?t know WRITE IN AGE",
 'And at what age, approximately, would you say men reach middle age?WRITE IN AGE',
 'And at what age, approximately, would you say men reach old age?WRITE IN AGE',
 'CARD 26To be considered an adult how important is it for a man to have left the parental home?Choose your answer from this card',
 'STILL CARD 26To be considered an adult how important is it for a man to have a full-time job?(Choose your answer from this card)',
 'STILL CARD 26To be considered an adult how important is it for a man to have lived with a spouse or partner?(Choose your answer from this card)',
 'STILL CARD 26And to be considered an adult how important is it for a man to have become a father?(Choose your answer from this card)',
 'STILL CARD 26To be considered old how important is it for a man to be physically frail?Choose your answer from this card',
 'STILL CARD 26To be considered old how important is it for a man to be a grandfather?(Choose your answer from this card)',
 'STILL CARD 26And to be considered old, how important is it for a man to need the help of others to look after him?(Choose your answer from this card)',