In [9]:
import pandas as pd
import json

In [10]:
from eu_survey_correlation.surveys.ess_scraper import ESSCodebookParser

parser = ESSCodebookParser("data/surveys/ess/ESS8e02_3 codebook.html")
variable_df = parser.parse()

In [11]:
variable_df

,variable_id,variable_name,variable_description,answer_id,answer_value
0,name,Title of dataset,Title of dataset,None,None
1,essround,ESS round,ESS round,None,None
2,edition,Edition,Edition,None,None
3,proddate,Production date,Production date,None,None
4,idno,Respondent's identification number,Respondent's identification number,None,None
...,...,...,...,...,...
12616,inwmme,"End of interview, month","End of interview, month",99,Not available*
12617,inwyye,"End of interview, year","End of interview, year",9999,Not available*
12618,inwehh,"End of interview, hour","End of interview, hour",99,Not available*
12619,inwemm,"End of interview, minute","End of interview, minute",99,Not available*
12620,inwtm,"Interview length in minutes, main questionnaire","Interview length in minutes, main questionnair...",None,None

In [ ]:
dico_id_name_var = {
    row["variable_id"]: row["variable_name"] for _, row in variable_df.iterrows()
}

In [13]:
value_df = pd.read_csv("data/surveys/ess/ESS8e02_3.csv")

/var/folders/j3/mm5hxwf11p18skbfc4mkjsgr0000gn/T/ipykernel_24344/1045449470.py:1: DtypeWarning: Columns (168) have mixed types. Specify dtype option on import or set low_memory=False.
  value_df = pd.read_csv("data/surveys/ess/ESS8e02_3.csv")

In [14]:
value_df.columns = [dico_id_name_var[col] for col in value_df.columns]

In [15]:
value_df

,Title of dataset,ESS round,Edition,Production date,Respondent's identification number,Country,Design weight,Post-stratification weight including design weight,Population size weight (must be combined with dweight or pspwght),Analysis weight,...,"Start of interview, month","Start of interview, year","Start of interview, hour","Start of interview, minute","End of interview, day of month","End of interview, month","End of interview, year","End of interview, hour","End of interview, minute","Interview length in minutes, main questionnaire"
0,ESS8e02_3,8,2.3,23.11.2023,1,AT,0.611677,1.178495,0.370393,0.436506,...,12,2016,7,37,5,12,2016,8,33,50.0
1,ESS8e02_3,8,2.3,23.11.2023,2,AT,1.223354,0.899471,0.370393,0.333158,...,11,2016,9,39,25,11,2016,11,10,86.0
2,ESS8e02_3,8,2.3,23.11.2023,4,AT,0.389058,0.315753,0.370393,0.116953,...,11,2016,17,17,22,11,2016,18,0,38.0
3,ESS8e02_3,8,2.3,23.11.2023,6,AT,0.642594,0.472467,0.370393,0.174999,...,10,2016,19,9,11,10,2016,19,59,46.0
4,ESS8e02_3,8,2.3,23.11.2023,10,AT,3.432402,2.246706,0.370393,0.832164,...,12,2016,10,31,1,12,2016,11,49,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44382,ESS8e02_3,8,2.3,23.11.2023,1303,SI,1.000000,0.835442,0.134491,0.112359,...,10,2016,7,30,19,10,2016,8,37,62.0
44383,ESS8e02_3,8,2.3,23.11.2023,1304,SI,1.000000,0.756328,0.134491,0.101719,...,9,2016,8,38,30,9,2016,9,45,60.0
44384,ESS8e02_3,8,2.3,23.11.2023,1305,SI,1.000000,0.856172,0.134491,0.115147,...,9,2016,9,9,26,9,2016,10,17,62.0
44385,ESS8e02_3,8,2.3,23.11.2023,1306,SI,1.000000,0.756328,0.134491,0.101719,...,11,2016,17,0,2,11,2016,18,25,78.0
44386,ESS8e02_3,8,2.3,23.11.2023,1307,SI,1.000000,0.802472,0.134491,0.107925,...,10,2016,16,9,25,10,2016,17,10,55.0

In [31]:
def check_row(
    row,
):
    print(row)
    for col in row.index:
        print(col)
        answer_value = variable_df[
            (variable_df["variable_name"] == col)
            & (variable_df["answer_id"] == row[col])
        ]
    row[col] = answer_value
    return row

In [35]:
variable_df.variable_description.unique().tolist()

['Title of dataset',
 'ESS round',
 'Edition',
 'Production date',
 "Respondent's identification number",
 'Country',
 'Design weight',
 'Post-stratification weight including design weight',
 'Population size weight (must be combined with dweight or pspwght)',
 'Analysis weight',
 'News about politics and current affairs, watching, reading or listening, in minutesOn a typical day, about how much time do you spend watching, reading or listening to news about politics and current affairs?Please give your answer in hours and minutes. INTERVIEWER: If no time spent, enter 00 00. WRITE IN DURATION',
 'Internet use, how oftenCARD 1People can use the internet on different devices such as computers, tablets and smartphones. How often do you use the internet on these or any other devices, whether for work or personal use?',
 'Internet use, how much time on typical day, in minutesASK IF MOST DAYS OR EVERY DAY AT A2 (code 4 or 5)On a typical day, about how much time do you spend using the internet on a computer, tablet, smartphone or other device, whether for work or personal use?Please give your answer in hours and minutes. INTERVIEWER: WRITE IN DURATION',
 "Most people can be trusted or you can't be too carefulASK ALL CARD 2Using this card, generally speaking, would you say that most people can be trusted, or that you can't be too careful in dealing with people? Please tell me on a score of 0 to 10, where 0 means you can't be too careful and 10 means that most people can be trusted.",
 'Most people try to take advantage of you, or try to be fairCARD 3Using this card, do you think that most people would try to take advantage of you if they got the chance, or would they try to be fair?',
 'Most of the time people helpful or mostly looking out for themselvesCARD 4Would you say that most of the time people try to be helpful or that they are mostly looking out for themselves?Please use this card.',
 'How interested in politicsHow interested would you say you are in politics - are you...READ OUT...',
 'Political system allows people to have a say in what government doesCARD 5How much would you say the political system in [country] allows people like you to have a say in what the government does?',
 'Able to take active role in political groupCARD 6How able do you think you are to take an active role in a group involved with political issues?',
 'Political system allows people to have influence on politicsCARD 7And how much would you say that the political system in [country] allows people like you to have an influence on politics?',
 'Confident in own ability to participate in politicsCARD 8And how confident are you in your own ability to participate in politics?',
 'Trust in the legal systemCARD 9Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...the legal system?READ OUT...',
 'Trust in the policeCARD 9Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...the police?READ OUT...',
 'Trust in politiciansCARD 9Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...politicians?READ OUT...',
 'Trust in the European ParliamentCARD 9Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...the European Parliament?READ OUT...',
 'Trust in the United NationsCARD 9Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...the United Nations?READ OUT...',
 'Trust in political partiesCARD 9Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...political parties?READ OUT...',
 "Trust in country's parliamentCARD 9Using this card, please tell me on a score of 0-10 how much you personally trust each of the institutions I read out. 0 means you do not trust an institution at all, and 10 means you have complete trust. Firstly... ...[country]'s parliament?READ OUT...",
 "Voted last national electionSome people don't vote nowadays for one reason or another. Did you vote in the last [country] national election in [month/year]?",
 'Party voted for in last national election, AustriaWhich party did you vote for in that election? (Austria)',
 'Party voted for in last national election, BelgiumWhich party did you vote for in that election? (Belgium)',
 'Party voted for in last national election, SwitzerlandWhich party did you vote for in that election? (Switzerland)',
 'Party voted for in last national election, CzechiaWhich party did you vote for in that election? (Czechia)',
 'Party voted for in last national election 1, GermanyWhich party did you vote for in that election? (Germany 1)',
 'Party voted for in last national election 2, GermanyWhich party did you vote for in that election? (Germany 2)',
 'Party voted for in last national election, EstoniaWhich party did you vote for in that election? (Estonia)',
 'Party voted for in last national election, SpainWhich party did you vote for in that election? (Spain)',
 'Party voted for in last national election, FinlandWhich party did you vote for in that election? (Finland)',
 'Party voted for in last national election, France (ballot 1)Which party did you vote for in that election? (France)',
 'Party voted for in last national election, United KingdomWhich party did you vote for in that election? (United Kingdom)',
 'Party voted for in last national election, HungaryWhich party did you vote for in that election? (Hungary)',
 'Party voted for in last national election, IrelandWhich party did you vote for in that election? (Ireland)',
 'Party voted for in last national election, IsraelWhich party did you vote for in that election? (Israel)',
 'Party voted for in last national election, IcelandWhich party did you vote for in that election? (Iceland)',
 'Party voted for in last national election, ItalyWhich party did you vote for in that election? (Italy)',
 'Party voted for in last national election 1, Lithuania (first vote, party)Which party did you vote for in that election? (Lithuania 1)',
 'Party voted for in last national election 2, Lithuania (second vote, party)Which party did you vote for in that election? (Lithuania 2)',
 'Party voted for in last national election 3, Lithuania (third vote, party)Which party did you vote for in that election? (Lithuania 3)',
 'Party voted for in last national election, NetherlandsWhich party did you vote for in that election? (Netherlands)',
 'Party voted for in last national election, NorwayWhich party did you vote for in that election? (Norway)',
 'Party voted for in last national election, PolandWhich party did you vote for in that election? (Poland)',
 'Party voted for in last national election, PortugalWhich party did you vote for in that election? (Portugal)',
 'Party voted for in last national election, Russian FederationWhich party did you vote for in that election? (Russian Federation)',
 'Party voted for in last national election, SwedenWhich party did you vote for in that election? (Sweden)',
 'Party voted for in last national election, SloveniaWhich party did you vote for in that election? (Slovenia)',
 'Contacted politician or government official last 12 monthsASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...contacted a politician, government or local government official?READ OUT',
 'Worked in political party or action group last 12 monthsASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...worked in a political party or action group?READ OUT',
 'Worked in another organisation or association last 12 monthsASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...worked in another organisation or association?READ OUT',
 'Worn or displayed campaign badge/sticker last 12 monthsASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...worn or displayed a campaign badge/sticker?READ OUT',
 'Signed petition last 12 monthsASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...signed a petition?READ OUT',
 'Taken part in lawful public demonstration last 12 monthsASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...taken part in a lawful public demonstration?READ OUT',
 'Boycotted certain products last 12 monthsASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...boycotted certain products?READ OUT',
 'Posted or shared anything about politics online last 12 monthsASK ALLThere are different ways of trying to improve things in [country] or help prevent things from going wrong. During the last 12 months, have you done any of the following? Have you... ...posted or shared anything about politics online, for example on blogs, via email or on social media such as Facebook or Twitter?READ OUT',
 'Feel closer to a particular party than all other partiesIs there a particular political party you feel closer to than all the other parties?',
 'Which party feel closer to, AustriaWhich one? (Austria)',
 'Which party feel closer to, BelgiumWhich one? (Belgium)',
 'Which party feel closer to, SwitzerlandWhich one? (Switzerland)',
 'Which party feel closer to, CzechiaWhich one? (Czechia)',
 'Which party feel closer to, GermanyWhich one? (Germany)',
 'Which party feel closer to, EstoniaWhich one? (Estonia)',
 'Which party feel closer to, SpainWhich one? (Spain)',
 'Which party feel closer to, FinlandWhich one? (Finland)',
 'Which party feel closer to, FranceWhich one? (France)',
 'Which party feel closer to, United KingdomWhich one? (United Kingdom)',
 'Which party feel closer to, HungaryWhich one? (Hungary)',
 'Which party feel closer to, IrelandWhich one? (Ireland)',
 'Which party feel closer to, IsraelWhich one? (Israel)',
 'Which party feel closer to, IcelandWhich one? (Iceland)',
 'Which party feel closer to, ItalyWhich one? (Italy)',
 'Which party feel closer to, LithuaniaWhich one? (Lithuania)',
 'Which party feel closer to, NetherlandsWhich one? (Netherlands)',
 'Which party feel closer to, NorwayWhich one? (Norway)',
 'Which party feel closer to, PolandWhich one? (Poland)',
 'Which party feel closer to, PortugalWhich one? (Portugal)',
 'Which party feel closer to, Russian FederationWhich one? (Russian Federation)',
 'Which party feel closer to, SwedenWhich one? (Sweden)',
 'Which party feel closer to, SloveniaWhich one? (Slovenia)',
 'How close to partyASK IF PARTY GIVEN AT B24 (codes 01 to xx)How close do you feel to this party? Do you feel that you are ...READ OUT...',
 "Placement on left right scaleASK ALL CARD 10In politics people sometimes talk of 'left' and 'right'. Using this card, where would you place yourself on this scale, where 0 means the left and 10 means the right?",
 'How satisfied with life as a wholeCARD 11All things considered, how satisfied are you with your life as a whole nowadays? Please answer using this card, where 0 means extremely dissatisfied and 10 means extremely satisfied.',
 'How satisfied with present state of economy in countrySTILL CARD 11On the whole how satisfied are you with the present state of the economy in [country]?Still use this card.',
 'How satisfied with the national governmentSTILL CARD 11Now thinking about the [country] government, how satisfied are you with the way it is doing its job?Still use this card.',
 'How satisfied with the way democracy works in countrySTILL CARD 11And on the whole, how satisfied are you with the way democracy works in [country]?Still use this card.',
 'State of education in country nowadaysCARD 12Now, using this card, please say what you think overall about the state of education in [country] nowadays?',
 'State of health services in country nowadaysSTILL CARD 12Still using this card, please say what you think overall about the state of health services in [country] nowadays?',
 'Government should reduce differences in income levelsCARD 13Using this card, please say to what extent you agree or disagree with each of the following statements. The government should take measures to reduce differences in income levelsREAD OUT EACH STATEMENT AND CODE IN GRID',
 'Men should have more right to job than women when jobs are scarceCARD 13Using this card, please say to what extent you agree or disagree with each of the following statements. When jobs are scarce, men should have more right to a job than women.READ OUT EACH STATEMENT AND CODE IN GRID',
 'Gays and lesbians free to live life as they wishCARD 13Using this card, please say to what extent you agree or disagree with each of the following statements. Gay men and lesbians should be free to live their own life as they wishREAD OUT EACH STATEMENT AND CODE IN GRID',
 'Ashamed if close family member gay or lesbianCARD 13Using this card, please say to what extent you agree or disagree with each of the following statements. If a close family member was a gay man or a lesbian, I would feel ashamed.READ OUT EACH STATEMENT AND CODE IN GRID',
 'Gay and lesbian couples right to adopt childrenCARD 13Using this card, please say to what extent you agree or disagree with each of the following statements. Gay male and lesbian couples should have the same rights to adopt children as straight couples.READ OUT EACH STATEMENT AND CODE IN GRID',
 'European Union: European unification go further or gone too farCARD 14Now thinking about the European Union, some say European unification should go further. Others say it has already gone too far. Using this card, what number on the scale best describes your position?',
 'Allow many/few immigrants of same race/ethnic group as majorityCARD 15Now, using this card, to what extent do you think [country] should allow people of the same race or ethnic group as most [country] people to come and live here?',
 'Allow many/few immigrants of different race/ethnic group from majoritySTILL CARD 15How about people of a different race or ethnic group from most [country] people?Still use this card.',
 'Allow many/few immigrants from poorer countries outside EuropeSTILL CARD 15How about people from the poorer countries outside Europe?Use the same card.',
 "Immigration bad or good for country's economyCARD 16Would you say it is generally bad or good for [country]'s economy that people come to live here from other countries?Please use this card.",
 "Country's cultural life undermined or enriched by immigrantsCARD 17And, using this card, would you say that [country]'s cultural life is generally undermined or enriched by people coming to live here from other countries?",
 'Immigrants make country worse or better place to liveCARD 18Is [country] made a worse or a better place to live by people coming to live here from other countries?Please use this card.',
 'How happy are youCARD 19Taking all things together, how happy would you say you are?Please use this card',
 'How often socially meet with friends, relatives or colleaguesCARD 20Using this card, how often do you meet socially with friends, relatives or work colleagues?',
 'How many people with whom you can discuss intimate and personal mattersCARD 21How many people, if any, are there with whom you can discuss intimate and personal matters?Choose your answer from this card.',
 'Take part in social activities compared to others of same ageCARD 22Compared to other people of your age, how often would you say you take part in social activities?Please use this card.',
 'Respondent or household member victim of burglary/assault last 5 yearsHave you or a member of your household been the victim of a burglary or assault in the last 5 years?',
 'Feeling of safety of walking alone in local area after darkHow safe do you - or would you - feel walking alone in this area after dark? Do - or would - you feel...READ OUT...',
 'Subjective general healthHow is your health in general? Would you say it is ...READ OUT...',
 'Hampered in daily activities by illness/disability/infirmity/mental problemAre you hampered in your daily activities in any way by any longstanding illness, or disability, infirmity or mental health problem? If yes, is that a lot or to some extent?',
 'How emotionally attached to [country]CARD 23How emotionally attached do you feel to [country]? Please choose a number from 0 to 10, where 0 means not at all emotionally attached and 10 means very emotionally attached.',
 'How emotionally attached to EuropeSTILL CARD 23And how emotionally attached do you feel to Europe?',
 'Belonging to particular religion or denominationDo you consider yourself as belonging to any particular religion or denomination?',
 'Religion or denomination belonging to at presentASK IF YES AT C11 (code 1)Which one?',
 'Religion or denomination belonging to at present, AustriaASK IF YES AT C11 (code 1)Which one? (Austria)',
 'Religion or denomination belonging to at present, BelgiumASK IF YES AT C11 (code 1)Which one? (Belgium)',
 'Religion or denomination belonging to at present, SwitzerlandASK IF YES AT C11 (code 1)Which one? (Switzerland)',
 'Religion or denomination belonging to at present, GermanyASK IF YES AT C11 (code 1)Which one? (Germany)',
 'Religion or denomination belonging to at present, FinlandASK IF YES AT C11 (code 1)Which one? (Finland)',
 'Religion or denomination belonging to at present, United KingdomASK IF YES AT C11 (code 1)Which one? (United Kingdom)',
 'Religion or denomination belonging to at present, HungaryASK IF YES AT C11 (code 1)Which one? (Hungary)',
 'Religion or denomination belonging to at present, IrelandASK IF YES AT C11 (code 1)Which one? (Ireland)',
 'Religion or denomination belonging to at present, IcelandASK IF YES AT C11 (code 1)Which one? (Iceland)',
 'Religion or denomination belonging to at present, LithuaniaASK IF YES AT C11 (code 1)Which one? (Lithuania)',
 'Religion or denomination belonging to at present, NetherlandsASK IF YES AT C11 (code 1)Which one? (Netherlands)',
 'Religion or denomination belonging to at present, NorwayASK IF YES AT C11 (code 1)Which one? (Norway)',
 'Religion or denomination belonging to at present, PolandASK IF YES AT C11 (code 1)Which one? (Poland)',
 'Religion or denomination belonging to at present, SwedenASK IF YES AT C11 (code 1)Which one? (Sweden)',
 "Ever belonging to particular religion or denominationASK IF NO RELIGION/DENOMINATION OR DON'T KNOW/REFUSAL AT C11 (codes 2, 7 or 8 at C11)Have you ever considered yourself as belonging to any particular religion or denomination?",